name: Deploy Business Management to VPS (Main)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            export PATH=/root/.nvm/versions/node/v21.7.3/bin:$PATH
            cd /home/ubuntu/main/business-management
            git pull origin main
            npm install
            cd ../data-hub
            npm install
            npm run db:generate
            cd ../business-management
            npm run build
            pm2 restart business-prod || pm2 start npm --name "business-prod" -- start -- -p 3004
